### PR TITLE
Custom syntax highlighting example

### PR DESCRIPTION
**Pull request by m-kus**
Since there's little documentation on how to add custom syntax via kernel

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Thanks @m-kus! We should be able to review this in the next few days hopefully.

I need to check how that can be achieved in the JupyterLab context...

**Comment by SylvainCorlay** [comment]
cc @blink1073 is there an equivalent to [this](https://github.com/jupyter/notebook/blob/b8b66332e2023e83d2ee04f83d8814f567e01a4e/notebook/static/notebook/js/kernelselector.js#L150-L183) in the context of JupyterLab?

**Comment by wolfv** [comment]
As far as I know it needs to be compiled as JLab extension.

**Comment by SylvainCorlay** [comment]
@wolfv this may be the *perfect* example usecase of the dynamic loader.

**Comment by JohanMabille** [comment]
This works only with the classic Notebook which was deprecated. Besides, JupyterLab will soon migrate to CodeMirror 6 where the highlighting syntax has been totally rewritten. We should advertise a generic way to provide custom syntax highlighting in Jupyter Lab.

**Pull request closed without merging**
