### PR TITLE
fix argument order in publish_status

### PR DESCRIPTION
**Pull request by DerThorsten**

### CODE REVIEW

**Comment by JohanMabille** [comment]
Can you also set `JSON_USE_IMPLICIT_CONVERSIONS` to 0 in `xeus.hpp`? This would catch potential remaining similar issues, and would avod to get hit again in the future.

**Comment by DerThorsten** [comment]
superseded by #396

**Comment by DerThorsten** [comment]
> JSON_USE_IMPLICIT_CONVERSIONS



> Can you also set `JSON_USE_IMPLICIT_CONVERSIONS` to 0 in `xeus.hpp`? This would catch potential remaining similar issues, and would avod to get hit again in the future.

this gives a lot of warnings  a la:

```
/Users/thorstenbeier/src/xeus/include/xeus/xeus.hpp:13:9: warning: 'JSON_USE_IMPLICIT_CONVERSIONS' macro redefined [-Wmacro-redefined]
   13 | #define JSON_USE_IMPLICIT_CONVERSIONS 0
      |         ^
/Users/thorstenbeier/micromamba/envs/xeus-wasm-dev/include/nlohmann/detail/macro_scope.hpp:467:13: note: previous definition is here
  467 |     #define JSON_USE_IMPLICIT_CONVERSIONS 1
```

**Comment by JohanMabille** [comment]
Ah, so it should probably be defined befor including nlohmann_json for the first time. Let's fix that in another PR.

**Pull request closed without merging**
